name: fluxstore
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/ProductSans-Medium.ttf
          weight: 500    
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700       
        - asset: assets/fonts/ProductSans-Light.ttf
          weight: 300
        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 100


    - family: Altoysitalicpersonalonly
      fonts:
        - asset: assets/fonts/Altoysitalicpersonalonly.ttf

    - family: DINNextLTPro
      fonts:
        - asset: assets/fonts/DINNextLTPro-Medium.ttf
          weight: 500

